sudo: required
services:
  - docker

before_install:    
  - docker build -t jhuang101/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true jhuang101/react-test npm test npm test
    
after_success:
  - docker build -t jhuang101/multi-client ./client
  - docker build -t jhuang101/multi-nginx ./nginx
  - docker build -t jhuang101/multi-server ./server
  - docker build -t jhuang101/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push jhuang101/multi-client
  - docker push jhuang101/multi-nginx
  - docker push jhuang101/multi-server
  - docker push jhuang101/multi-worker